Update column types in SQL storage models
crowdsecurity/python-capi-sdk pull request #15
Opened 2024-02-08 13:51 UTC by TheophileDiot

## Description
This pull request addresses compatibility issues with MySQL databases caused by the TEXT column type. MySQL requires specific sizes in schema definitions, which were not being met by the TEXT type. To resolve this, the column types in SQL storage models are updated to String(512).

## Changes Made
### Modified Files
- **src/models/sql_storage.py**: Updated column types from TEXT to String(512) to meet MySQL schema requirements.

2024-02-08 16:18 UTC, rr404 requested changes
OK to adjust string size, but lets do it more precisely.
Also we need to find a TEXT alternative for LONG strings, some MUST accept unlimited sizes like scenarios

2024-02-08 16:18 UTC, rr404 commented on src/cscapi/sql_storage.py
> +    token = Column(String(512))
[critical] (!) token are currently over 1000char long !

2024-02-08 16:21 UTC, rr404 commented
MySQL supports the TEXT type, would it be a python sqlalchemy issue ?

Two things:
* OK to change to sized string to be more optimal (and non breaking, example "token" >1088)
* But we need to keep unsized strings for some fields like "scenarios"

@TheophileDiot is your mysql DB really not suporting TEXT type ? or is it when python tries to convert the sqlalchemy type TEXT ?

2024-02-08 16:26 UTC, rr404 commented
@julienloizelet Lets make a list or cleverly thought string size that leave room for evolution where needed while being precise when we know it wont change
Example:
* MachineDBModel.machine_id, we could go up to 256 and be future proof i guess
* MachineDBModel.scenarios need to stay unlimited
* ...
* DecisionDBModel.origin we know it's never gonna be much, even if we one day have the list name in there it won't go over 64
* DecisionDBModel.duration we could probably size it to 32 ir less what are the possible longest values?
* DecisionDBModel.until is it a timestamp or date? it's probably something that has and will keep a fixed size
* ....

2024-02-09 06:10 UTC, julienloizelet commented
Hi @TheophileDiot and @rr404 ,

I've tested with a mysql 5.7 database.

TEXT is supported but we have an error on the machine_id field because it is an index (primary key): 

`BLOB/TEXT column 'machine_id' used in key specification without a key length`.

See https://stackoverflow.com/a/1827099/7497291 for some details.

If we change TEXT to String(256) for machine_id, it works great.

(Tested also with mariadb 10.8 and postgresql 11)

I will create a PR to fix that.

Other improvements (like setting accurate length for all fields) can be done later, I guess.

Thanks

2024-02-09 08:41 UTC, closed without merging

2024-02-09 08:41 UTC, rr404 commented
Closing this PR because it will be fixed by https://github.com/crowdsecurity/python-capi-sdk/pull/17