MongoDB storage
crowdsecurity/python-capi-sdk pull request #27
Opened 2024-03-25 11:27 UTC by fgibertoni

Added implementation of MongoDB storage interface and its tests.
The new interface is not used by default but has an optional dependency that can be installed with `pip install cscapi[mongodb]`.

The `get_signals` method has been hard to implement with MongoDB, so if you see any improvements that can be done I will gladly accept them :)

2024-03-28 08:32 UTC, julienloizelet requested changes
Thanks for this PR.

2024-03-28 08:32 UTC, julienloizelet commented on src/cscapi/mongodb_storage.py
> +        host="mongodb://127.0.0.1:27017/cscapi",
Is it possible to modify this so that an user can pass a custom host ?
Maybe with something like the `connection_string` in the `__init__`  method of sql_storage here: https://github.com/crowdsecurity/python-capi-sdk/blob/main/src/cscapi/sql_storage.py#L146

2024-03-28 08:32 UTC, julienloizelet commented on src/cscapi/mongodb_storage.py
> +            if not signal.alert_id:
I've tested to add a batch of signals with a simple script that does:
```
signals = [
    create_signal(
        attacker_ip=args.ip,
        scenario=args.scenario,
        created_at=args.created_at,
        machine_id=machine_id,
        context=context if context else [],
    )
]

for x in range(5000):
    client.add_signals(signals)
```

But, with the current code, only 2 signals were created: 1 with an id>0 and one with a -1 id. (Because, on each loop, a signal with alert_id=-1 was updated.

I came up with the following definition of `update_or_create_signals` : 

```
    def update_or_create_signal(self, signal: SignalModel) -> bool:
        # Filter out the keys for embedded documents to handle them separately
        signal_filtered = {k: v for k, v in asdict(signal).items() if k not in ["source", "context", "decisions"]}

        created = False  # Flag to track if a new document is created

        # Only proceed if alert_id is not None
        if signal.alert_id is not None:
            try:
                signal_db_model = SignalDBModel.objects.get(alert_id=signal.alert_id)
            except SignalDBModel.DoesNotExist:
                # If it doesn't exist, create a new one with all the data including alert_id
                signal_db_model = SignalDBModel(**signal_filtered)
                created = True
        else:
            # If alert_id is None, directly create a new model with the provided data
            signal_db_model = SignalDBModel(**signal_filtered)
            created = True

        # Update or set the source, context, and decisions fields
        if signal.source:
            signal_db_model.source = SourceDBModel(**asdict(signal.source))
        if signal.context:
            signal_db_model.context = [ContextDBModel(**asdict(ctx)) for ctx in signal.context]
        if signal.decisions:
            signal_db_model.decisions = [DecisionDBModel(**asdict(dec)) for dec in signal.decisions]

        # Save the model (works for both creating a new document and updating an existing one)
        signal_db_model.save()

        return created
```

If it works for you too, could you please update the code accordingly ?

2024-03-28 08:32 UTC, julienloizelet commented on src/cscapi/mongodb_storage.py
> +
For consistency with sql table name, could you please set the same table name by adding this line: 
```
meta = {"collection": "signal_models"}
```

2024-03-28 08:32 UTC, julienloizelet commented on src/cscapi/mongodb_storage.py
> +
For consistency with sql table name, could you please set the same table name by adding this line: 
```
meta = {"collection": "machine_models"}
```

2024-03-28 09:52 UTC, fgibertoni commented on src/cscapi/mongodb_storage.py
> +            if not signal.alert_id:
That's a really nice catch, thank you for reporting.

Your code is working also for me, I'm updating my code accordingly.

2024-03-29 01:16 UTC, julienloizelet commented on src/cscapi/mongodb_storage.py
> +                host="mongodb://127.0.0.1:27017/cscapi",
Here, I will modify with host=connection_string.

2024-03-29 01:18 UTC, julienloizelet approved these changes
LGTM. Thanks for this !

After merge, I will just try to add some github action tests for this mongo implementation and probably will modify slightly unit test to use some env connection_string.

Then, I will publish a new release.

2024-03-29 01:23 UTC, merged